# -*- coding: utf-8 -*-
"""Week-3_Assignment-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wd9hbuZ5QQaaCF93z7SH97d3Z4TbroGn
"""

import pandas as pd
from google.colab import files

uploaded = files.upload()

print(uploaded.keys())

df = pd.read_csv('agriculture_yield_dataset.csv')
print(df.head())

# Q1 Dataset Overview

# Number of rows and columns
print("Rows and Columns:", df.shape)

# Column names
print("\nColumn Names:")
print(df.columns.tolist())

# First 10 records
print("\nFirst 10 Records:")
print(df.head(10))

# Q2 Data Types and Missing Values

# Data types
print("Data Types:")
print(df.dtypes)

# Missing values count
print("\nMissing Values:")
print(df.isnull().sum())

# Columns having missing values
missing_cols = df.columns[df.isnull().sum() > 0]

print("\nColumns with Missing Values:")
print(missing_cols.tolist())

# Q3 Descriptive Statistics

summary = df.describe()

print(summary)

# Highest mean value
highest_mean_feature = summary.loc['mean'].idxmax()
highest_mean_value = summary.loc['mean'].max()

print("\nFeature with Highest Mean:")
print(highest_mean_feature, highest_mean_value)

# Highest standard deviation
highest_std_feature = summary.loc['std'].idxmax()
highest_std_value = summary.loc['std'].max()

print("\nFeature with Highest Standard Deviation:")
print(highest_std_feature, highest_std_value)

# Q4 Histograms

import matplotlib.pyplot as plt

columns = [
    'rainfall_mm',
    'temperature_c',
    'fertilizer_kg',
    'yield_ton_per_hectare'
]

for col in columns:
    plt.figure(figsize=(6,4))
    plt.hist(df[col], bins=20)
    plt.title(f'Histogram of {col}')
    plt.xlabel(col)
    plt.ylabel('Frequency')
    plt.show()

# Q5 Crop Type Analysis

import seaborn as sns
import matplotlib.pyplot as plt

# Count records
crop_counts = df['crop_type'].value_counts()

print(crop_counts)

# Count plot
plt.figure(figsize=(8,5))
sns.countplot(x='crop_type', data=df)
plt.title("Crop Type Count")
plt.xticks(rotation=45)
plt.show()

# Most frequent crop
print("\nMost Frequent Crop:")
print(crop_counts.idxmax())

# Q6 Soil Type Analysis

soil_counts = df['soil_type'].value_counts()

print(soil_counts)

# Count plot
plt.figure(figsize=(8,5))
sns.countplot(x='soil_type', data=df)
plt.title("Soil Type Count")
plt.xticks(rotation=45)
plt.show()

# Most common soil type
print("\nMost Common Soil Type:")
print(soil_counts.idxmax())

# Q7 Yield Distribution

plt.figure(figsize=(7,5))
plt.hist(df['yield_ton_per_hectare'], bins=20)
plt.title("Yield Distribution")
plt.xlabel("Yield (ton/hectare)")
plt.ylabel("Frequency")
plt.show()

# Q8 Scatter Plots

# Rainfall vs Yield
plt.figure(figsize=(6,4))
plt.scatter(df['rainfall_mm'], df['yield_ton_per_hectare'])
plt.xlabel('Rainfall (mm)')
plt.ylabel('Yield (ton/hectare)')
plt.title('Rainfall vs Yield')
plt.show()

# Fertilizer vs Yield
plt.figure(figsize=(6,4))
plt.scatter(df['fertilizer_kg'], df['yield_ton_per_hectare'])
plt.xlabel('Fertilizer (kg)')
plt.ylabel('Yield (ton/hectare)')
plt.title('Fertilizer vs Yield')
plt.show()

# Q9 Correlation Matrix and Heatmap

import seaborn as sns

# Numerical columns only
corr_matrix = df.select_dtypes(include=['number']).corr()

print(corr_matrix)

# Heatmap
plt.figure(figsize=(10,8))
sns.heatmap(corr_matrix,
            annot=True,
            cmap='coolwarm',
            fmt='.2f')

plt.title('Correlation Heatmap')
plt.show()

# Correlation with yield
yield_corr = corr_matrix['yield_ton_per_hectare'].sort_values(ascending=False)

print("\nCorrelation with Yield:")
print(yield_corr)

# Top 3 correlated features (excluding yield itself)
print("\nTop 3 Features Correlated with Yield:")
print(yield_corr.drop('yield_ton_per_hectare').head(3))

# Q10 Average Yield by Crop Type

crop_yield = df.groupby('crop_type')['yield_ton_per_hectare'].mean()

print("Average Yield by Crop Type:")
print(crop_yield)

print("\nHighest Yield Crop:")
print(crop_yield.idxmax(), crop_yield.max())


# Average Yield by Soil Type

soil_yield = df.groupby('soil_type')['yield_ton_per_hectare'].mean()

print("\nAverage Yield by Soil Type:")
print(soil_yield)

print("\nHighest Yield Soil Type:")
print(soil_yield.idxmax(), soil_yield.max())

# Q11 One-Hot Encoding

# Identify categorical columns
categorical_cols = df.select_dtypes(include=['object']).columns

print("Categorical Columns:")
print(categorical_cols.tolist())

# One-Hot Encoding
df_encoded = pd.get_dummies(
    df,
    columns=categorical_cols,
    drop_first=True
)

print("\nFirst 5 Rows After Encoding:")
print(df_encoded.head())

# Q12 Feature Selection

target_column = 'yield_ton_per_hectare'

X = df_encoded.drop(target_column, axis=1)
y = df_encoded[target_column]

print("Target Variable:")
print(target_column)

print("\nX Shape:", X.shape)
print("y Shape:", y.shape)

# Q13 Train-Test Split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("X_train Shape:", X_train.shape)
print("X_test Shape:", X_test.shape)
print("y_train Shape:", y_train.shape)
print("y_test Shape:", y_test.shape)

# Q14 Linear Regression

from sklearn.linear_model import LinearRegression
import pandas as pd

model = LinearRegression()

model.fit(X_train, y_train)

# Intercept
print("Intercept:")
print(model.intercept_)

# Coefficients
coef_df = pd.DataFrame({
    'Feature': X.columns,
    'Coefficient': model.coef_
})

print("\nModel Coefficients:")
print(coef_df)

# Highest positive coefficient
highest_positive = coef_df.loc[
    coef_df['Coefficient'].idxmax()
]

print("\nFeature with Highest Positive Coefficient:")
print(highest_positive)